source 'https://rubygems.org'

gem 'fog', '~> 1.26.0'
gem 'net-ssh'
gem 'google-api-client', '~> 0.6', '>= 0.6.2'

group :test do
  gem 'rake'
  gem 'rspec'
  gem 'simplecov', '~> 0.7.1', :require => false
end
