source 'https://rubygems.org'

gem 'rake'

# These gems are used by the provisioner
group :dependencies do
  gem 'json'
  gem 'logger'
  gem 'net-scp'
  gem 'rest_client'
end

group :test do
  gem 'rspec'
  gem 'simplecov', '~> 0.7.1', :require => false
end
