#!/bin/bash
#
# Perform necessary loom-provisioner setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

mkdir -p /var/log/loom /var/run/loom /etc/default /etc/logrotate.d
chown -R loom:loom /opt/loom/provisioner
chown -R loom:loom /var/log/loom
chown -R loom:loom /var/run/loom

# Add defaults
if [ ! -f /etc/default/loom-provisioner ] ; then
  echo "export LOOM_NUM_WORKERS=5" > /etc/default/loom-provisioner
  echo "export LOOM_SERVER_URI=http://localhost:55054" >> /etc/default/loom-provisioner
  echo "export LOOM_LOG_DIR=/var/log/loom" >> /etc/default/loom-provisioner
  echo "export LOOM_LOG_LEVEL=info" >> /etc/default/loom-provisioner
fi

ln -sf /opt/loom/provisioner/bin/init-loom-provisioner /etc/init.d/loom-provisioner
ln -sf /opt/loom/provisioner/etc/logrotate.d/loom-provisioner /etc/logrotate.d/loom-provisioner

exit 0
