#!/bin/bash
#
# Copyright 2012-2014, Continuuity, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# chkconfig: 2345 96 15
# description: Starts and stops the loom-ngui service
# 
### BEGIN INIT INFO
# Provides:          loom-ngui
# Short-Description: Loom NGUI
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:    $network
# Required-Stop:     $network
# Should-Start:
# Should-Stop:
### END INIT INFO

# source /etc/default/loom-ngui
[ -f /etc/default/loom-ngui ] && source /etc/default/loom-ngui

# create pid dir owned by loom user
mkdir -p /var/run/loom
chown -R loom:loom /var/run/loom

# drop permissions to loom user and run service script

if [[ $UID -eq 0 ]]; then
    su loom -c "cd /opt/loom/ngui/bin; exec ./ngui.sh $*"
else
    cd /opt/loom/ngui/bin; exec ./ngui.sh $*
fi

