#!/bin/bash
#
# Perform necessary loom-ui setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

mkdir -p /var/log/loom /var/run/loom /etc/default /etc/logrotate.d
chown -R loom:loom /opt/loom/ui
chown -R loom:loom /var/log/loom
chown -R loom:loom /var/run/loom

# Add defaults
if [ ! -f /etc/default/loom-ui ] ; then
  echo "export LOOM_SERVER_URI=http://localhost:55054" > /etc/default/loom-ui
  echo "export LOOM_LOG_DIR=/var/log/loom" >> /etc/default/loom-ui
  echo "export LOOM_UI_PORT=8100" >> /etc/default/loom-ui
fi

ln -sf /opt/loom/ui/bin/init-loom-ui /etc/init.d/loom-ui
ln -sf /opt/loom/ui/etc/logrotate.d/loom-ui /etc/logrotate.d/loom-ui

exit 0
