#!/usr/bin/env rake
# encoding: UTF-8

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:rspec)

# rubocop rake task
desc 'Ruby style guide linter'
task :rubocop do
  sh 'rubocop -D'
end

task default: %w(rubocop rspec)
