#!/bin/bash
#
# Perform necessary loom-server setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

mkdir -p /var/log/loom /var/run/loom /etc/loom/conf.dist /etc/default /var/loom/data /etc/logrotate.d /etc/loom/conf.loom
cp /opt/loom/server/conf/* /etc/loom/conf.dist
chown -R loom:loom /opt/loom
chown -R loom:loom /var/loom
chown -R loom:loom /var/log/loom
chown -R loom:loom /var/run/loom
chown -R loom:loom /etc/loom/conf.dist
chown -R loom:loom /etc/loom/conf.loom

# Add defaults
if [ ! -f /etc/default/loom-server ] ; then
  echo "export LOOM_LOG_DIR=/var/log/loom" > /etc/default/loom-server
  echo "# Uncomment the following to enable JMX metrics for Loom Server" >> /etc/default/loom-server
  echo "#export LOOM_JMX_OPTS=\"-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010" \
    "-Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false" \
    "-Dcom.sun.management.jmxremote.ssl=false\"" >> /etc/default/loom-server
  echo "# Uncomment the following to enable verbose GC logging" >> /etc/default/loom-server
  echo "#export LOOM_GC_OPTS=\"-verbose:gc -Xloggc:/var/log/loom/loom-server.gc.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=1M\"" >> /etc/default/loom-server
  echo "# edit the following to add any other desired java options" >> /etc/default/loom-server
  echo "export LOOM_JAVA_OPTS=\"-XX:+UseConcMarkSweepGC -XX:+UseParNewGC \${LOOM_GC_OPTS} \${LOOM_JMX_OPTS}\"" >> /etc/default/loom-server
fi

# Copy default configuration (first time, only)
for i in $(cd /etc/loom/conf.dist ; ls -1) ; do
  if [ -e /etc/loom/conf.loom/${i} ] ; then
    continue
  else
    cp -f /etc/loom/conf.dist/${i} /etc/loom/conf.loom
  fi
done

update-alternatives --install /etc/loom/conf loom-conf /etc/loom/conf.dist 10
update-alternatives --install /etc/loom/conf loom-conf /etc/loom/conf.loom 10
ln -sf /opt/loom/server/bin/init-loom-server /etc/init.d/loom-server
ln -sf /opt/loom/server/etc/logrotate.d/loom-server /etc/logrotate.d/loom-server

exit 0
