#!/bin/bash
#
# Perform necessary loom-provisioner setup steps
# prior to installing package.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

update-alternatives --remove loom-conf /etc/loom/conf.dist

exit 0
